### PR TITLE
tweaks of example for msd

### PR DESCRIPTION
**Pull request by jiangtong1000**
resolve the bug in #265

### CODE REVIEW

**Review by fdmalone — CHANGES_REQUESTED** [review]
Thanks for this! I think the real problem here was that I didn't include a test for the subsequent AFQMC simulation in the CI examples check. My suggestion would be to 1) Add this check or 2) delete the legacy example and just use your nice new run_afqmc.py script. I think 2 is preferred but you'll delete this example from the legacy_dirs dict in https://github.com/JoonhoLee-Group/ipie/blob/develop/dev/run_tests.py#L96

**Comment by fdmalone** [comment]
We should also just remove the legacy examples.

**Comment by jiangtong1000** [comment]
ok. I just delete the legacy test for this example, and the new script will be automatically tested I guess. I am not sure if we should just delete the legacy way, or there is a bug need to be fixed when the ndets = 1?

**Comment by fdmalone** [comment]
LGTM. Open an issue to track the ndet = 1 case and we can come back to it later.

**Comment by fdmalone** [comment]
Ah, you need to add the scf script to the run_afqmc.py script as we seem to have adopted a one script workflow in the examples.

**Review by fdmalone — APPROVED** [review]

**Pull request merged**
