### PR TITLE
Revert "update walker ovlp before computing energy"

### PR DESCRIPTION
**Pull request by linusjoonho**

### CODE REVIEW

**Comment by linusjoonho** [comment]
@fdmalone @jiangtong1000 I actually remember this bug now. The way I fixed last time was to compute overlap consistently in the end of the propagation function. @jiangtong1000 could you not achieve what you wanted to do by evaluating overlap properly in the propagator?

**Comment by fdmalone** [comment]
Yeah I think we want only really want to mutate the walkers state very explicitly (propagation and QR factorization) otherwise we can see very subtle bugs. I don't think the estimators should be doing this.

**Comment by jiangtong1000** [comment]
> @fdmalone @jiangtong1000 I actually remember this bug now. The way I fixed last time was to compute overlap consistently in the end of the propagation function. @jiangtong1000 could you not achieve what you wanted to do by evaluating overlap properly in the propagator?

ok, I will test that and let you know.

**Comment by jiangtong1000** [comment]
then this is not a bug, for current code. Let's keep it in the current shape for the moment. I just need to pay attention to the ovlp update of my own code where I need reortho done during propagation. Thanks for pointing out!

**Review by fdmalone — APPROVED** [review]

**Pull request merged**
